### ISSUE TITLE
Results/presentation of this work?

### ISSUE THREAD

**Issue by sckott** [kmanlove/ParticipationInComputing#1]
hi there, nice work on this. 

Curious if you put out a blog post or did a presentation on this I can reference?  hoping to talk about great use cases for the software we (ropensci) make

**Comment by kmanlove** [comment]
Thanks! It was an interesting project, and the gender and rMetadata packages were both really useful! I'm hoping to revisit the actual numbers again in the future to do something a bit more formal, but for the time-being, there are slides here: http://slides.com/keziamanlove/digitalsilence, and a blogpost here: http://ciddgsa.com/2015/06/09/why-arent-there-more-women-in-ecological-computing. I'll pass the word along if I wind up producing a more formal analysis -- very grateful to you all for building the tools!

**Comment by sckott** [comment]
Thanks for the links!  You might also find https://github.com/ropensci/fulltext useful if you're doing text mining of literature.
